name: wannaplayfoot
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  curved_navigation_bar: ^1.0.6
  flutter_login: ^5.0.0  
  firebase_auth: ^5.1.2
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1
  firebase_core: ^3.2.0
  flutter_bloc: ^8.1.6



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
    - assets/splash_animation.json
